### ISSUE TITLE
Could you support LaTeXStrings.jl?

### ISSUE THREAD

**Issue by Photonico** [mbaz/Gaston.jl#115]
Gaston works well in Jupyter even I use windows. 
LaTeXStrings.jl can provide the effect of latex in plotting. but it is unavailable in Gaston.
![problem](https://raw.githubusercontent.com/ConAntares/Problems/master/2019/20190804b.png)
![problem](https://raw.githubusercontent.com/ConAntares/Problems/master/2019/20190804c.png)

**Comment by mbaz** [comment]
@Photonico As far as i can see, this is unsupported by Gnuplot itself, and is not something that can be done from Gaston.

Gaston already supports enhanced text mode (see page 27 in the Gnuplot 5.2 manual). That provides some minimal math support.

Otherwise, you'd need to use a terminal that supports Latex, such as `epslatex` or `tikz`. I want to support the `tikz` terminal eventually, but it probably will not happen soon.
