### ISSUE TITLE
Error when setting plot title

### ISSUE THREAD

**Issue by nxtruong** [mbaz/Gaston.jl#138]
I'm using `Gaston v1.0.2` and GNUPLOT v5.2.8 on MacOS, with Julia 1.4.1. GNUPLOT runs fine. When I tried a simple example of Gaston where the plot title is set, for example `plot(1:10,title="A simple plot")`, I got the following error:
```
Gnuplot returned an error message:
│
│ gnuplot> plot '/var/folders/ls/r2_fp3yj53jdf92t42z8c7mh0000gn/T/jl_Lt9cZU' i 0  title A simple plot
│                                                                                       ^
│          line 0: expecting "title" for plot
│
└ @ Gaston ~/.julia/packages/Gaston/FSgDg/src/gaston_llplot.jl:182
```

After updating GNUPLOT to version 5.4.0 on MacOS, the above command returned the following error instead:
```
Gnuplot returned an error message:
│            line 0: undefined variable: A
│
└ @ Gaston ~/.julia/packages/Gaston/FSgDg/src/gaston_llplot.jl:182
```

**Comment by mbaz** [comment]
The problem is that `title` requires a string in quotes as argument, for example `'A simple plot'`. Gaston uses the convention that arguments are passed to gnuplot without quotes; this works for example when setting the plot type:  `plot(x, y, with = "points")` passes the argument `points` (no quotes) to gnuplot.

There are a few ways to include the quotes:

* Quote the argument yourself: `plot(x, y, title = "'A simple plot'")`.
* Use a symbol: `plot(x, y, title = :A_simple_plot)`.
* Escape the quotes: `plot(x, y, title = "\"A simple plot\"")`.

As an aside: in gnuplot, `title` used as in your example sets what in other programs is called the "legend". If you want to set the title of the actual plot, you need to wrap `title` in an `Axes` object: `plot(x, y, Axes(title = "'A simple plot'"))`. The ambiguity comes from gnuplot itself, which uses `title` in these two different ways.
