### ISSUE TITLE
Path to temp file written across top of image

### ISSUE THREAD

**Issue by MooersLab** [mbaz/Gaston.jl#141]
The path to the temp file is written across top of the the saved image when saved from the REPL.
I get the save behavior when the commands are run in IJulia.

I am using Julia 1.5.0 on a Mac OS 10.15.6

```julia
using Gaston
set(term="dumb")
t = 0:0.001:1
plot(t, sin.(2π*5*t))
save(term="png",output="testGaston.png")
save(term="pdf",output="testGaston.pdf")
```

[testGaston.pdf](https://github.com/mbaz/Gaston.jl/files/5137073/testGaston.pdf)
![testGaston](https://user-images.githubusercontent.com/15176203/91458232-e2e36a00-e84a-11ea-9dfd-66559189e9f3.png)

**Comment by mbaz** [comment]
This is gnuplot's default behavior: it uses the file path name as a legend. Gaston respects gnuplot's defaults, which is why you get this.

There are two ways to avoid seeing the path to the temp file. The recommended way is to create a gnuplot configuration file. In addition to removing the default legend, you can configure line styles, colors, margins, etcetera. See https://mbaz.github.io/Gaston.jl/stable/#Gnuplot-configuration-1 -- the line that removes the default legend is `set key noautotitle`.

The second way to do remove the default legend is to set the legend to empty:
```
using Gaston
set(term="dumb")
t = 0:0.001:1
plot(t, sin.(2π*5*t), legend = "''")
save(term="png",output="testGaston.png")
save(term="pdf",output="testGaston.pdf")
```
The main disadvantage of this method is that you need to pass an extra argument in every single plot.

Feel free to reopen if you still have issues.
