### ISSUE TITLE
latex support in labels

### ISSUE THREAD

**Issue by berceanu** [mbaz/Gaston.jl#31]
is there any way one can render labels/titles using latex syntax, i.e. "k_x [\mu^{-1}]"?

**Comment by mbaz** [comment]
Gaston is limited by what gnuplot can do. It does enable enhanced text mode in all terminals (see "Enhanced Text Mode" in gnuplot's documentation, page 24 in the 5.0 manual).

Fortunately, both Julia and gnuplot understand UTF 8, so you can get the label you want by using μ instead of \mu. For example, this works as expected:

    plot(sin(1:10),"xlabel","α_1^{-2}+Σ_i k+∞")
