### ISSUE TITLE
problem with Range1 using Gaston

### ISSUE THREAD

**Issue by my-little-repository** [mbaz/Gaston.jl#38]
I just upgraded julia today from master [(ersion 0.4.0-dev+6093 (2015-07-20 07:55 UTC)) and Gaston using the package manager. I now get an error when I try to start Gaston.

      julia> using Gaston
      ERROR: LoadError: LoadError: UndefVarError: Range1 not defined
       in include at ./boot.jl:254
       in include_from_node1 at ./loading.jl:187
       in include at ./boot.jl:254
       in include_from_node1 at ./loading.jl:187
       in require at ./loading.jl:141
      while loading /home/mlr/.julia/v0.4/Gaston/src/gaston_types.jl, in expression starting on line 161
      while loading /home/mlr/.julia/v0.4/Gaston/src/Gaston.jl, in expression starting on line 26

I can see that the issue (Range1 is now UnitRange) is now fixed in master. Maybe it is possible to update the version in the package manager?

**Comment by mbaz** [comment]
Thank you for your report. I haven't tagged a new release of Gaston because
I'm still working on a couple of features I'd like to include in the next
release, and the documentation for the features I've already implemented is
not yet complete.

However, you should be able to get Gaston's master by running
`Pkg.checkout("Gaston")` in Julia. Then, running `Pkg.status()` should show
Gaston with the "master" label.

Please let me know if this works for you.

**Comment by my-little-repository** [comment]
Yes, it works, thanks.
