### ISSUE TITLE
gnuplot_send() method crashing

### ISSUE THREAD

**Issue by francilioaraujo** [mbaz/Gaston.jl#56]
When I try to use the following code in IJulia

    using Gaston
    gnuplot_send("set view 67,25")
    surf(-3:.1:3,-3:0.1:3,(x,y)->cos(x)*sin(y),"plotstyle","points","xlabel","coord 1","ylabel","coord 2","zlabel","coord 3","title","surf demo","color","blue")

I get the following error

    MethodError: no method matching write(::Int64, ::String)
    Closest candidates are:
      write(::AbstractString, ::Any...) at io.jl:107
      write(::IO, ::String) at strings/string.jl:244
      write(::IO, ::AbstractString) at strings/io.jl:71
      ...
    
     in gnuplot_send(::String) at /home/francilio/.julia/v0.5/Gaston/src/gaston_lowlvl.jl:8

Perhaps the `gnuplot_state.fid[1]` field is setted wrong in the first run.

**Comment by francilioaraujo** [comment]
I figured out how to circunvent this problem. Before using `gnuplot_send()` I call `figure()` and it runs OK.

**Comment by mbaz** [comment]
Thanks for the report. You can also plot first, and set the view afterwards:

    using Gaston
    surf(-3:.1:3,-3:0.1:3,(x,y)->cos(x)*sin(y),"plotstyle","points","xlabel","coord 1","ylabel","coord 2","zlabel","coord 3","title","surf demo","color","blue")
    gnuplot_send("set view 67,25")
    figure(1)

The final `figure(1)` is needed to force gnuplot to re-plot with the new view parameters.

I'll think about a possible solution, such as adding a check for a figure existing before accepting `set` commands. However, my gut feeling is  that there is no good general solution, because `gnuplot_send` is too general; some `set` commands expect a figure to exist, and others (like `set output`) don't.
