### ISSUE TITLE
Add a `reset` command to return configuration to default state

### ISSUE THREAD

**Issue by CarloLucibello** [mbaz/Gaston.jl#64]
As a complement to `set` maybe it could be usefull to also have an `unset` method

**Comment by mbaz** [comment]
The only use case I see for `unset` is when you temporarily change a setting, and want to revert to the original value shortly afterwards. I do this, for example, [here](https://github.com/mbaz/Gaston.jl/blob/f0ccb1213b6cbec35421084d6f6867a42b8d743c/src/gaston_hilvl.jl#L349) where I temporarily change the terminal type while saving a file.

Providing `unset`, though, will involve large changes in the code. Currently, `set` actually modifies _all_ parameters, but those not provided by the user are set to their old value. This simplifies the code _a lot_.

The ability to `unset` a paremeter will require large code changes, and I think the benefit is limited, especially since the workaround is only two extra lines.

A simpler alternative would be to provide a `reset` function that returns every single parameter to their default value. Would that be useful?

**Comment by CarloLucibello** [comment]
Right, I opened the issue not as a consequence of a specific usecase but just for symmetry with the set method. On the other hand I'm sure `reset` would be very useful instead.

**Comment by mbaz** [comment]
OK! I'll add this to my TODO list.
