### ISSUE TITLE
Contents of figure when saving

### ISSUE THREAD

**Issue by PetrKryslUCSD** [mbaz/Gaston.jl#82]
I had two figures created in succession. I started saving the figures into PDF files. When I saved the figure that was opened first, after the save it immediately switched to displaying the contents of the figure that was created second. So at that point both figures showed the same contents.

I presume this is a gnuplot thing, as I don't think Gaston is not in control at that point anymore?

**Comment by mbaz** [comment]
Could you provide the commands you're using? I'd like to reproduce this behavior. Are you doing something like this:

```
figure(1)
plot(1:10)
printfigure(....)
figure(2)
plot(10:20)
printfigure(.....)
```

Plotting using the same figure handle in quick succession is challenging because Gaston writes the coordinates to a file, tells gnuplot to plot, and then proceeds to write the coordinates for the next plot. It is easy for Gaston to overwrite the file before gnuplot is done reading it.

I take care of that [here](https://github.com/mbaz/Gaston.jl/blob/e3174d7998f2dd1217885cd5af730485f0f00755/src/gaston_llplot.jl#L176). The idea is that Gaston asks gnuplot to output a known string on STDOUT and waits until that happens. At that point, we can be sure that gnuplot is done plotting and the data file can be safely overwritten. I wonder if you found a situation where that safeguard doesn't work.

On the other hand, using separate handles for each plot (created with `figure`) should always work, because they use different data files.

**Comment by PetrKryslUCSD** [comment]
Here is an example: I have two figures open, and I save the two figures in turn into PDF files.
https://www.dropbox.com/s/j5w65zjxookxuow/FFsplit-180314-175547.flv?dl=0

**Comment by mbaz** [comment]
So, you're saving the figures from each figure window, right? You're not using `printfigure`?

If so, then I have never tried doing it. I'll try to reproduce this.

**Comment by mbaz** [comment]
@PetrKryslUCSD I think recent changes should have fixed this issue -- I can't reproduce it in any case. If you're still using Gaston, could you please update to master and retry?
