### ISSUE TITLE
Inline display

### ISSUE THREAD

**Issue by kim-tom** [mbaz/Gaston.jl#91]
Hello. Thank you for your convenient packages.
I wish I could use quiver and y2label in Jupiter notebook.
I am now using quiver by using Gaston.send(). But it seemes that it opens new gnuplot window. I wish I could display quiver graph on the screen of Jupiter notebook. 
Can I use %matplotlib inline, which enables pythonists to display graph in jupyternotebook?

**Comment by mbaz** [comment]
I think there's an issue open for adding quiver and y2label support -- I'm going to look into supporting those when time allows.

Instead of using `Gaston.send()`, I recommend using `gpcom` as an argument to `plot()`. The format is `gpcom="gnuplot command"`, where the string `"gnuplot_command"` is sent to gnuplot as the last command before actually plotting. You can see an example here: https://nbviewer.jupyter.org/github/mbaz/Gaston.jl/blob/master/doc/gaston-tutorial.ipynb#Low-level-interaction-with-gnuplot

**Comment by kim-tom** [comment]
Thank you for your kindness!
I will try it!

**Comment by mbaz** [comment]
Fixed in v0.10.0. See new docs: https://mbaz.github.io/Gaston.jl/v0.10.0/
