### ISSUE TITLE
Weird warning

### ISSUE THREAD

**Issue by PetrKryslUCSD** [mbaz/Gaston.jl#94]
The master says:

```
┌ Warning: `warn()` is deprecated, use `@warn` instead.
│   caller = #warn#777(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::String) at deprecated.jl:1029
└ @ Base deprecated.jl:1029
WARNING: Gnuplot returned an error message:
  GastonDone
)
```
The plot finished correctly. So I suppose this warning shouldn't really be issued?

**Comment by mbaz** [comment]
Indeed -- I noticed that a few weeks ago, but I couldn't find the cause then, and then I was 100% busy with work.

I have some free time now, so hopefully I can fix this soon. When this is fixed, I'll do a release (to address https://github.com/mbaz/Gaston.jl/issues/93)

**Comment by hycakir** [comment]
Simply change `warn("some strings")` with `@warn "some strings"` for version >= 0.7.  Together with https://github.com/mbaz/Gaston.jl/pull/96 will make Gaston work with julia 1.0 and 0.7. Only one test doesn't pass after the revisions due to `is_windows`. The function `is_windows()` should be replaced with Sys.iswindows() for version >= 0.7 in test files.

**Comment by mbaz** [comment]
Thanks @hycakir . I hope to make these changes and tag a new release soon.
